export type PlanTier = "Basic" | "Pro" | "Enterprise";
export type LoginFrequency = "Daily" | "Weekly" | "Rarely";
export type RiskCategory = "Healthy" | "Under-utilized" | "At-risk";

export interface Customer {
  id: string;
  name: string;
  email: string;
  planTier: PlanTier;
  monthlyValue: number;
  accountAgeDays: number;
  loginFrequency: LoginFrequency;
  dailyUsageMins: number;
  lastActive: string;
  lastSupportTicket: string;
  churnRisk: number;
  riskCategory: RiskCategory;
  explanation: string;
  recommendedAction: string;
}

export const customers: Customer[] = [
  {
    id: "cust-001",
    name: "Ariana Foster",
    email: "ariana.foster@brightleaf.co",
    planTier: "Enterprise",
    monthlyValue: 1499,
    accountAgeDays: 812,
    loginFrequency: "Daily",
    dailyUsageMins: 96,
    lastActive: "2026-07-17",
    lastSupportTicket: "Asked about SSO setup for new hires, resolved quickly.",
    churnRisk: 8,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: consistent daily usage and no unresolved support issues indicate strong product engagement.",
    recommendedAction: "Placeholder recommendation: invite to case-study program and offer early access to new features.",
  },
  {
    id: "cust-002",
    name: "Marcus Chen",
    email: "marcus.chen@loopwave.io",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 40,
    loginFrequency: "Rarely",
    dailyUsageMins: 4,
    lastActive: "2026-06-02",
    lastSupportTicket: "Complained that onboarding was confusing and left ticket unresolved.",
    churnRisk: 88,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: sharp drop in login frequency combined with an unresolved onboarding complaint signals high churn probability.",
    recommendedAction: "Placeholder recommendation: trigger a personal outreach call and offer a guided onboarding session.",
  },
  {
    id: "cust-003",
    name: "Priya Nair",
    email: "priya.nair@fernhill.com",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 210,
    loginFrequency: "Weekly",
    dailyUsageMins: 18,
    lastActive: "2026-07-10",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 42,
    riskCategory: "Under-utilized",
    explanation: "Placeholder AI explanation: usage is stable but well below the plan's typical engagement level, suggesting untapped value.",
    recommendedAction: "Placeholder recommendation: send a feature-highlight email showcasing underused automation tools.",
  },
  {
    id: "cust-004",
    name: "Devon Blake",
    email: "devon.blake@ridgeworks.net",
    planTier: "Enterprise",
    monthlyValue: 1899,
    accountAgeDays: 1120,
    loginFrequency: "Daily",
    dailyUsageMins: 143,
    lastActive: "2026-07-18",
    lastSupportTicket: "Requested a new integration, delivered and praised.",
    churnRisk: 5,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: long tenure, heavy daily usage, and positive support interactions point to a highly satisfied account.",
    recommendedAction: "Placeholder recommendation: propose an upsell to the advanced analytics add-on.",
  },
  {
    id: "cust-005",
    name: "Sofia Reyes",
    email: "sofia.reyes@brambleco.com",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 95,
    loginFrequency: "Rarely",
    dailyUsageMins: 6,
    lastActive: "2026-06-20",
    lastSupportTicket: "Billing question about a failed payment, resolved.",
    churnRisk: 75,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: infrequent logins alongside a recent billing hiccup are strong churn indicators for accounts under 6 months old.",
    recommendedAction: "Placeholder recommendation: offer a loyalty discount and confirm payment method is up to date.",
  },
  {
    id: "cust-006",
    name: "Tobias Lindqvist",
    email: "tobias.lindqvist@northgate.se",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 640,
    loginFrequency: "Weekly",
    dailyUsageMins: 22,
    lastActive: "2026-07-14",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 30,
    riskCategory: "Under-utilized",
    explanation: "Placeholder AI explanation: steady but shallow engagement over a long tenure suggests the account has plateaued below its potential.",
    recommendedAction: "Placeholder recommendation: recommend a plan review call to align features with actual needs.",
  },
  {
    id: "cust-007",
    name: "Hannah Whitfield",
    email: "hannah.whitfield@cedarpath.org",
    planTier: "Enterprise",
    monthlyValue: 1499,
    accountAgeDays: 55,
    loginFrequency: "Daily",
    dailyUsageMins: 110,
    lastActive: "2026-07-18",
    lastSupportTicket: "Asked for a training session for their team, scheduled.",
    churnRisk: 12,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: strong onboarding momentum with daily usage well above the Enterprise average.",
    recommendedAction: "Placeholder recommendation: check in after the training session to reinforce adoption.",
  },
  {
    id: "cust-008",
    name: "Julian Ortiz",
    email: "julian.ortiz@westmark.biz",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 300,
    loginFrequency: "Rarely",
    dailyUsageMins: 3,
    lastActive: "2026-05-28",
    lastSupportTicket: "Frustrated email about a bug that blocked their workflow for a week.",
    churnRisk: 91,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: a severe unresolved bug complaint combined with near-zero recent usage puts this account in critical risk territory.",
    recommendedAction: "Placeholder recommendation: escalate to engineering for a priority fix and issue a service credit.",
  },
  {
    id: "cust-009",
    name: "Isabelle Moreau",
    email: "isabelle.moreau@lumenfield.fr",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 18,
    loginFrequency: "Daily",
    dailyUsageMins: 40,
    lastActive: "2026-07-17",
    lastSupportTicket: "Asked a quick how-to question, resolved same day.",
    churnRisk: 15,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: new account showing enthusiastic early engagement, a positive predictor of retention.",
    recommendedAction: "Placeholder recommendation: enroll in a 30-day new-customer nurture sequence.",
  },
  {
    id: "cust-010",
    name: "Ethan Kowalski",
    email: "ethan.kowalski@ironvale.com",
    planTier: "Enterprise",
    monthlyValue: 1899,
    accountAgeDays: 430,
    loginFrequency: "Weekly",
    dailyUsageMins: 35,
    lastActive: "2026-07-05",
    lastSupportTicket: "Mentioned considering a competitor tool during a support chat.",
    churnRisk: 68,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: a mention of a competitor combined with declining weekly usage on a high-value account warrants immediate attention.",
    recommendedAction: "Placeholder recommendation: schedule an executive business review to re-establish value.",
  },
  {
    id: "cust-011",
    name: "Grace Adeyemi",
    email: "grace.adeyemi@palmgrove.ng",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 500,
    loginFrequency: "Daily",
    dailyUsageMins: 88,
    lastActive: "2026-07-18",
    lastSupportTicket: "Requested an export feature, added to roadmap and communicated.",
    churnRisk: 10,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: long-standing daily user with a responsive support history shows strong loyalty signals.",
    recommendedAction: "Placeholder recommendation: ask for a referral or testimonial given high satisfaction.",
  },
  {
    id: "cust-012",
    name: "Noah Bergström",
    email: "noah.bergstrom@fjordline.se",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 150,
    loginFrequency: "Weekly",
    dailyUsageMins: 20,
    lastActive: "2026-07-11",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 38,
    riskCategory: "Under-utilized",
    explanation: "Placeholder AI explanation: moderate but capped engagement suggests the account hasn't discovered the product's full workflow.",
    recommendedAction: "Placeholder recommendation: offer a free 1:1 workflow audit call.",
  },
  {
    id: "cust-013",
    name: "Camille Dupont",
    email: "camille.dupont@solstice.fr",
    planTier: "Enterprise",
    monthlyValue: 1499,
    accountAgeDays: 900,
    loginFrequency: "Daily",
    dailyUsageMins: 120,
    lastActive: "2026-07-18",
    lastSupportTicket: "Praised a recent feature release directly to support.",
    churnRisk: 4,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: near-maximum engagement and unsolicited positive feedback make this a model account.",
    recommendedAction: "Placeholder recommendation: invite to the customer advisory board.",
  },
  {
    id: "cust-014",
    name: "Liam O'Sullivan",
    email: "liam.osullivan@brackenhurst.ie",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 70,
    loginFrequency: "Rarely",
    dailyUsageMins: 5,
    lastActive: "2026-06-15",
    lastSupportTicket: "Asked for a refund after a confusing invoice, resolved with credit.",
    churnRisk: 80,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: a refund request paired with minimal usage in a young account signals buyer's remorse and imminent churn.",
    recommendedAction: "Placeholder recommendation: proactively clarify billing and offer a downgrade option to retain at lower value.",
  },
  {
    id: "cust-015",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@sakuraworks.jp",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 400,
    loginFrequency: "Daily",
    dailyUsageMins: 55,
    lastActive: "2026-07-17",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 14,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: high daily usage relative to plan tier indicates strong perceived value.",
    recommendedAction: "Placeholder recommendation: suggest an upgrade to Pro given usage patterns.",
  },
  {
    id: "cust-016",
    name: "Oliver Kim",
    email: "oliver.kim@haventree.com",
    planTier: "Enterprise",
    monthlyValue: 1899,
    accountAgeDays: 22,
    loginFrequency: "Weekly",
    dailyUsageMins: 25,
    lastActive: "2026-07-09",
    lastSupportTicket: "Asked several setup questions during onboarding, all resolved.",
    churnRisk: 48,
    riskCategory: "Under-utilized",
    explanation: "Placeholder AI explanation: new high-value account with below-expected activation could stall without early intervention.",
    recommendedAction: "Placeholder recommendation: assign a dedicated onboarding specialist for the first 90 days.",
  },
  {
    id: "cust-017",
    name: "Amara Okafor",
    email: "amara.okafor@rivergate.ng",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 260,
    loginFrequency: "Daily",
    dailyUsageMins: 74,
    lastActive: "2026-07-16",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 18,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: consistent daily activity over an extended period reflects a well-embedded workflow.",
    recommendedAction: "Placeholder recommendation: share advanced tips to deepen feature adoption.",
  },
  {
    id: "cust-018",
    name: "Felix Baumann",
    email: "felix.baumann@steinbrook.de",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 88,
    loginFrequency: "Rarely",
    dailyUsageMins: 2,
    lastActive: "2026-06-01",
    lastSupportTicket: "Never opened the welcome email or logged in after week one.",
    churnRisk: 85,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: near-total inactivity since the first week is one of the strongest churn predictors in the model.",
    recommendedAction: "Placeholder recommendation: send a win-back email with a limited-time incentive.",
  },
  {
    id: "cust-019",
    name: "Ingrid Solheim",
    email: "ingrid.solheim@fjellro.no",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 610,
    loginFrequency: "Weekly",
    dailyUsageMins: 28,
    lastActive: "2026-07-12",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 35,
    riskCategory: "Under-utilized",
    explanation: "Placeholder AI explanation: long tenure with stagnant weekly usage suggests routine but shallow reliance on the product.",
    recommendedAction: "Placeholder recommendation: reintroduce key features via a personalized product tour.",
  },
  {
    id: "cust-020",
    name: "Rafael Santos",
    email: "rafael.santos@baiaverde.br",
    planTier: "Enterprise",
    monthlyValue: 1499,
    accountAgeDays: 730,
    loginFrequency: "Daily",
    dailyUsageMins: 105,
    lastActive: "2026-07-18",
    lastSupportTicket: "Requested a custom report, delivered ahead of schedule.",
    churnRisk: 7,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: two-year tenure with sustained heavy usage and fast support resolutions indicate a durable relationship.",
    recommendedAction: "Placeholder recommendation: propose a multi-year contract with a loyalty discount.",
  },
  {
    id: "cust-021",
    name: "Chloe Bennett",
    email: "chloe.bennett@thornfield.co.uk",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 33,
    loginFrequency: "Rarely",
    dailyUsageMins: 6,
    lastActive: "2026-06-25",
    lastSupportTicket: "Asked how to cancel, retained after a discount offer.",
    churnRisk: 72,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: a prior cancellation inquiry combined with continued low usage means retention efforts have not fully taken hold.",
    recommendedAction: "Placeholder recommendation: follow up personally to confirm the discount resolved their concerns.",
  },
  {
    id: "cust-022",
    name: "Viktor Petrov",
    email: "viktor.petrov@severstar.ru",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 145,
    loginFrequency: "Daily",
    dailyUsageMins: 92,
    lastActive: "2026-07-18",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 9,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: heavy consistent usage with a clean support history reflects a self-sufficient, satisfied user.",
    recommendedAction: "Placeholder recommendation: highlight power-user badge and invite to beta program.",
  },
  {
    id: "cust-023",
    name: "Mei Lin",
    email: "mei.lin@goldenharbor.sg",
    planTier: "Enterprise",
    monthlyValue: 1899,
    accountAgeDays: 380,
    loginFrequency: "Weekly",
    dailyUsageMins: 30,
    lastActive: "2026-07-08",
    lastSupportTicket: "Flagged that a key report was missing data, still investigating.",
    churnRisk: 60,
    riskCategory: "At-risk",
    explanation: "Placeholder AI explanation: an unresolved data-accuracy complaint on a high-value account is a critical trust risk.",
    recommendedAction: "Placeholder recommendation: prioritize the open ticket and follow up with a personal apology call.",
  },
  {
    id: "cust-024",
    name: "Daniel Achebe",
    email: "daniel.achebe@emeraldbay.ng",
    planTier: "Basic",
    monthlyValue: 49,
    accountAgeDays: 500,
    loginFrequency: "Weekly",
    dailyUsageMins: 16,
    lastActive: "2026-07-13",
    lastSupportTicket: "No tickets filed.",
    churnRisk: 33,
    riskCategory: "Under-utilized",
    explanation: "Placeholder AI explanation: modest, unchanging usage over a long history suggests the account is coasting rather than growing.",
    recommendedAction: "Placeholder recommendation: send a curated list of features matched to their use case.",
  },
  {
    id: "cust-025",
    name: "Zoe Harrington",
    email: "zoe.harrington@willowmere.com",
    planTier: "Pro",
    monthlyValue: 299,
    accountAgeDays: 12,
    loginFrequency: "Daily",
    dailyUsageMins: 60,
    lastActive: "2026-07-17",
    lastSupportTicket: "Asked a setup question during onboarding, resolved same day.",
    churnRisk: 20,
    riskCategory: "Healthy",
    explanation: "Placeholder AI explanation: brand-new account showing above-average early engagement is a positive early signal.",
    recommendedAction: "Placeholder recommendation: continue the onboarding drip sequence and check in at day 30.",
  },
];

export function getCustomerById(id: string): Customer | undefined {
  return customers.find((c) => c.id === id);
}

export function getTotalCustomers(): number {
  return customers.length;
}

export function getAtRiskCustomers(): Customer[] {
  return customers.filter((c) => c.riskCategory === "At-risk");
}

export function getPercentAtRisk(): number {
  return Math.round((getAtRiskCustomers().length / customers.length) * 100);
}

export function getRevenueAtRisk(): number {
  return getAtRiskCustomers().reduce((sum, c) => sum + c.monthlyValue, 0);
}

export function getMRR(): number {
  return customers.reduce((sum, c) => sum + c.monthlyValue, 0);
}

export function getRiskDistribution(): { category: RiskCategory; count: number }[] {
  const categories: RiskCategory[] = ["Healthy", "Under-utilized", "At-risk"];
  return categories.map((category) => ({
    category,
    count: customers.filter((c) => c.riskCategory === category).length,
  }));
}

export function getTopCustomersByRisk(limit: number = 10): Customer[] {
  return [...customers].sort((a, b) => b.churnRisk - a.churnRisk).slice(0, limit);
}
